import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class LocalizationService {
  private translations: { [key: string]: { [lang: string]: string } } = {
    // Common
    'welcome': {
      en: 'Welcome',
      hi: 'स्वागत है',
      ta: 'வரவேற்கிறோம்',
      te: 'స్వాగతం',
      kn: 'ಸ್ವಾಗತ',
      ml: 'സ്വാഗതം',
      mr: 'स्वागत आहे',
      gu: 'સ્વાગત છે',
      bn: 'স্বাগতম',
      pa: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    },
    'profile': {
      en: 'Profile',
      hi: 'प्रोफ़ाइल',
      ta: 'சுயவிவரம்',
      te: 'ప్రొఫైల్',
      kn: 'ಪ್ರೊಫೈಲ್',
      ml: 'പ്രൊഫൈൽ',
      mr: 'प्रोफाइल',
      gu: 'પ્રોફાઇલ',
      bn: 'প্রোফাইল',
      pa: 'ਪ੍ਰੋਫਾਈਲ',
    },
    'search': {
      en: 'Search',
      hi: 'खोज',
      ta: 'தேடல்',
      te: 'శోధన',
      kn: 'ಹುಡುಕಿ',
      ml: 'തിരയുക',
      mr: 'शोध',
      gu: 'શોધો',
      bn: 'অনুসন্ধান',
      pa: 'ਖੋਜ',
    },
    'back': {
      en: 'Back',
      hi: 'वापस',
      ta: 'பின்',
      te: 'వెనక్కి',
      kn: 'ಹಿಂದೆ',
      ml: 'പിന്നിലേക്ക്',
      mr: 'मागे',
      gu: 'પાછળ',
      bn: 'পিছনে',
      pa: 'ਪਿੱਛੇ',
    },
    'loading': {
      en: 'Loading...',
      hi: 'लोड हो रहा है...',
      ta: 'ஏற்றுகிறது...',
      te: 'లోడ్ అవుతోంది...',
      kn: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      ml: 'ലോഡ് ചെയ്യുന്നു...',
      mr: 'लोड होत आहे...',
      gu: 'લોડ થઈ રહ્યું છે...',
      bn: 'লোড হচ্ছে...',
      pa: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    },
    'loadingProfile': {
      en: 'Loading profile...',
      hi: 'प्रोफ़ाइल लोड हो रही है...',
      ta: 'சுயவிவரம் ஏற்றுகிறது...',
      te: 'ప్రొఫైల్ లోడ్ అవుతోంది...',
      kn: 'ಪ್ರೊಫೈಲ್ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
      ml: 'പ്രൊഫൈൽ ലോഡ് ചെയ്യുന്നു...',
      mr: 'प्रोफाइल लोड होत आहे...',
      gu: 'પ્રોફાઇલ લોડ થઈ રહ્યું છે...',
      bn: 'প্রোফাইল লোড হচ্ছে...',
      pa: 'ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    },
    'profileNotFound': {
      en: 'Profile not found',
      hi: 'प्रोफ़ाइल नहीं मिली',
      ta: 'சுயவிவரம் கிடைக்கவில்லை',
      te: 'ప్రొఫైల్ దొరకలేదు',
      kn: 'ಪ್ರೊಫೈಲ್ ಕಂಡುಬಂದಿಲ್ಲ',
      ml: 'പ്രൊഫൈൽ കണ്ടെത്തിയില്ല',
      mr: 'प्रोफाइल सापडली नाही',
      gu: 'પ્રોફાઇલ મળી નથી',
      bn: 'প্রোফাইল পাওয়া যায়নি',
      pa: 'ਪ੍ਰੋਫਾਈਲ ਨਹੀਂ ਮਿਲੀ',
    },
    'goBack': {
      en: 'Go back',
      hi: 'वापस जाएं',
      ta: 'திரும்பிச் செல்ல',
      te: 'వెనక్కి వెళ్ళండి',
      kn: 'ಹಿಂದೆ ಹೋಗಿ',
      ml: 'പിന്നിലേക്ക് പോകുക',
      mr: 'मागे जा',
      gu: 'પાછળ જાઓ',
      bn: 'ফিরে যান',
      pa: 'ਪਿੱਛੇ ਜਾਓ',
    },
    'verified': {
      en: 'Verified',
      hi: 'सत्यापित',
      ta: 'சரிபார்க்கப்பட்டது',
      te: 'ధృవీకరించబడింది',
      kn: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      ml: 'സ്ഥിരീകരിച്ചു',
      mr: 'सत्यापित',
      gu: 'ચકાસાયેલ',
      bn: 'যাচাইকৃত',
      pa: 'ਪੁਸ਼ਟੀ ਕੀਤੀ',
    },
    'featured': {
      en: 'Featured',
      hi: 'विशेष',
      ta: 'முன்னிலைப்படுத்தப்பட்டது',
      te: 'విశేషాలు',
      kn: 'ವಿಶೇಷ',
      ml: 'പ്രദർശിപ്പിച്ചത്',
      mr: 'वैशिष्ट्यपूर्ण',
      gu: 'વિશેષ',
      bn: 'বিশেষ',
      pa: 'ਵਿਸ਼ੇਸ਼',
    },
    'connectNow': {
      en: 'Connect Now',
      hi: 'अभी कनेक्ट करें',
      ta: 'இப்போது இணைக்கவும்',
      te: 'ఇప్పుడు కనెక్ట్ చేయండి',
      kn: 'ಈಗ ಸಂಪರ್ಕಿಸಿ',
      ml: 'ഇപ്പോൾ കണക്റ്റ് ചെയ്യുക',
      mr: 'आत्ता कनेक्ट करा',
      gu: 'હવે કનેક્ટ કરો',
      bn: 'এখনই সংযোগ করুন',
      pa: 'ਹੁਣ ਕਨੈਕਟ ਕਰੋ',
    },
    'requestSent': {
      en: 'Request Sent',
      hi: 'अनुरोध भेजा गया',
      ta: 'கோரிக்கை அனுப்பப்பட்டது',
      te: 'అభ్యర్థన పంపబడింది',
      kn: 'ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ',
      ml: 'അഭ്യർത്ഥന അയച്ചു',
      mr: 'विनंती पाठवली',
      gu: 'વિનંતી મોકલી',
      bn: 'অনুরোধ পাঠানো হয়েছে',
      pa: 'ਬੇਨਤੀ ਭੇਜੀ ਗਈ',
    },
    'accepted': {
      en: 'Accepted',
      hi: 'स्वीकृत',
      ta: 'ஏற்கப்பட்டது',
      te: 'అంగీకరించబడింది',
      kn: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ',
      ml: 'സ്വീകരിച്ചു',
      mr: 'स्वीकारले',
      gu: 'સ્વીકૃત',
      bn: 'গ্রহণ করা হয়েছে',
      pa: 'ਸਵੀਕਾਰ ਕੀਤਾ',
    },
    'rejected': {
      en: 'Rejected',
      hi: 'अस्वीकृत',
      ta: 'நிராகரிக்கப்பட்டது',
      te: 'తిరస్కరించబడింది',
      kn: 'ತಿರಸ್ಕರಿಸಲಾಗಿದೆ',
      ml: 'നിരസിച്ചു',
      mr: 'नाकारले',
      gu: 'નકારી',
      bn: 'প্রত্যাখ্যান করা হয়েছে',
      pa: 'ਅਸਵੀਕਾਰ ਕੀਤਾ',
    },
    'shortlist': {
      en: 'Shortlist',
      hi: 'शॉर्टलिस्ट',
      ta: 'குறுகிய பட்டியல்',
      te: 'శార్ట్‌లిస్ట్',
      kn: 'ಶಾರ್ಟ್‌ಲಿಸ್ಟ್',
      ml: 'ഷോർട്ട്‌ലിസ്റ്റ്',
      mr: 'शॉर्टलिस्ट',
      gu: 'શોર્ટલિસ્ટ',
      bn: 'শর্টলিস্ট',
      pa: 'ਸ਼ਾਰਟਲਿਸਟ',
    },
    'shortlisted': {
      en: 'Shortlisted',
      hi: 'शॉर्टलिस्ट किया गया',
      ta: 'குறுகிய பட்டியலில்',
      te: 'శార్ట్‌లిస్ట్ చేయబడింది',
      kn: 'ಶಾರ್ಟ್‌ಲಿಸ್ಟ್ ಮಾಡಲಾಗಿದೆ',
      ml: 'ഷോർട്ട്‌ലിസ്റ്റ് ചെയ്തു',
      mr: 'शॉर्टलिस्ट केले',
      gu: 'શોર્ટલિસ્ટ કર્યું',
      bn: 'শর্টলিস্ট করা হয়েছে',
      pa: 'ਸ਼ਾਰਟਲਿਸਟ ਕੀਤਾ',
    },
    'aboutMe': {
      en: 'About Me',
      hi: 'मेरे बारे में',
      ta: 'என்னைப் பற்றி',
      te: 'నా గురించి',
      kn: 'ನನ್ನ ಬಗ್ಗೆ',
      ml: 'എന്നെക്കുറിച്ച്',
      mr: 'माझ्याबद्दल',
      gu: 'મારા વિશે',
      bn: 'আমার সম্পর্কে',
      pa: 'ਮੇਰੇ ਬਾਰੇ',
    },
    'basicInformation': {
      en: 'Basic Information',
      hi: 'मूल जानकारी',
      ta: 'அடிப்படை தகவல்',
      te: 'ప్రాథమిక సమాచారం',
      kn: 'ಮೂಲಭೂತ ಮಾಹಿತಿ',
      ml: 'അടിസ്ഥാന വിവരങ്ങൾ',
      mr: 'मूलभूत माहिती',
      gu: 'મૂળભૂત માહિતી',
      bn: 'মৌলিক তথ্য',
      pa: 'ਮੂਲ ਜਾਣਕਾਰੀ',
    },
    'religionCulture': {
      en: 'Religion & Culture',
      hi: 'धर्म और संस्कृति',
      ta: 'மதம் மற்றும் கலாச்சாரம்',
      te: 'మతం మరియు సంస్కృతి',
      kn: 'ಧರ್ಮ ಮತ್ತು ಸಂಸ್ಕೃತಿ',
      ml: 'മതവും സംസ്കാരവും',
      mr: 'धर्म आणि संस्कृती',
      gu: 'ધર્મ અને સંસ્કૃતિ',
      bn: 'ধর্ম ও সংস্কৃতি',
      pa: 'ਧਰਮ ਅਤੇ ਸੱਭਿਆਚਾਰ',
    },
    'educationCareer': {
      en: 'Education & Career',
      hi: 'शिक्षा और करियर',
      ta: 'கல்வி மற்றும் தொழில்',
      te: 'విద్య మరియు కెరీర్',
      kn: 'ಶಿಕ್ಷಣ ಮತ್ತು ವೃತ್ತಿ',
      ml: 'വിദ്യാഭ്യാസവും കരിയറും',
      mr: 'शिक्षण आणि करिअर',
      gu: 'શિક્ષણ અને કારકિર્દી',
      bn: 'শিক্ষা ও ক্যারিয়ার',
      pa: 'ਸਿੱਖਿਆ ਅਤੇ ਕਰੀਅਰ',
    },
    'familyInformation': {
      en: 'Family Information',
      hi: 'पारिवारिक जानकारी',
      ta: 'குடும்ப தகவல்',
      te: 'కుటుంబ సమాచారం',
      kn: 'ಕುಟುಂಬದ ಮಾಹಿತಿ',
      ml: 'കുടുംബ വിവരങ്ങൾ',
      mr: 'कुटुंब माहिती',
      gu: 'કુટુંબની માહિતી',
      bn: 'পারিবারিক তথ্য',
      pa: 'ਪਰਿਵਾਰਕ ਜਾਣਕਾਰੀ',
    },
    'lifestyle': {
      en: 'Lifestyle',
      hi: 'जीवनशैली',
      ta: 'வாழ்க்கை முறை',
      te: 'జీవనశైలి',
      kn: 'ಜೀವನಶೈಲಿ',
      ml: 'ജീവിതശൈലി',
      mr: 'जीवनशैली',
      gu: 'જીવનશૈલી',
      bn: 'জীবনযাত্রা',
      pa: 'ਜੀਵਨ ਸ਼ੈਲੀ',
    },
    'location': {
      en: 'Location',
      hi: 'स्थान',
      ta: 'இடம்',
      te: 'స్థానం',
      kn: 'ಸ್ಥಳ',
      ml: 'സ്ഥാനം',
      mr: 'स्थान',
      gu: 'સ્થાન',
      bn: 'অবস্থান',
      pa: 'ਸਥਾਨ',
    },
    'gender': {
      en: 'Gender',
      hi: 'लिंग',
      ta: 'பாலினம்',
      te: 'లింగం',
      kn: 'ಲಿಂಗ',
      ml: 'ലിംഗം',
      mr: 'लिंग',
      gu: 'લિંગ',
      bn: 'লিঙ্গ',
      pa: 'ਲਿੰਗ',
    },
    'age': {
      en: 'Age',
      hi: 'उम्र',
      ta: 'வயது',
      te: 'వయసు',
      kn: 'ವಯಸ್ಸು',
      ml: 'പ്രായം',
      mr: 'वय',
      gu: 'ઉંમર',
      bn: 'বয়স',
      pa: 'ਉਮਰ',
    },
    'years': {
      en: 'years',
      hi: 'वर्ष',
      ta: 'ஆண்டுகள்',
      te: 'సంవత్సరాలు',
      kn: 'ವರ್ಷಗಳು',
      ml: 'വർഷങ്ങൾ',
      mr: 'वर्षे',
      gu: 'વર્ષ',
      bn: 'বছর',
      pa: 'ਸਾਲ',
    },
    'height': {
      en: 'Height',
      hi: 'ऊंचाई',
      ta: 'உயரம்',
      te: 'ఎత్తు',
      kn: 'ಎತ್ತರ',
      ml: 'ഉയരം',
      mr: 'उंची',
      gu: 'ઊંચાઈ',
      bn: 'উচ্চতা',
      pa: 'ਉਚਾਈ',
    },
    'status': {
      en: 'Status',
      hi: 'स्थिति',
      ta: 'நிலை',
      te: 'స్థితి',
      kn: 'ಸ್ಥಿತಿ',
      ml: 'പദവി',
      mr: 'स्थिती',
      gu: 'સ્થિતિ',
      bn: 'অবস্থা',
      pa: 'ਸਥਿਤੀ',
    },
    'maritalStatus': {
      en: 'Marital Status',
      hi: 'वैवाहिक स्थिति',
      ta: 'திருமண நிலை',
      te: 'వివాహ స్థితి',
      kn: 'ವಿವಾಹಿತ ಸ್ಥಿತಿ',
      ml: 'വിവാഹ സ്ഥിതി',
      mr: 'वैवाहिक स्थिती',
      gu: 'વૈવાહિક સ્થિતિ',
      bn: 'বৈবাহিক অবস্থা',
      pa: 'ਵਿਆਹੁਤਾ ਸਥਿਤੀ',
    },
    'dateOfBirth': {
      en: 'Date of Birth',
      hi: 'जन्म तिथि',
      ta: 'பிறந்த தேதி',
      te: 'జనన తేదీ',
      kn: 'ಜನನ ದಿನಾಂಕ',
      ml: 'ജനന തീയതി',
      mr: 'जन्मतारीख',
      gu: 'જન્મ તારીખ',
      bn: 'জন্ম তারিখ',
      pa: 'ਜਨਮ ਮਿਤੀ',
    },
    'manglik': {
      en: 'Manglik',
      hi: 'मंगलिक',
      ta: 'மங்களிக்',
      te: 'మంగళిక',
      kn: 'ಮಂಗಳಿಕ',
      ml: 'മംഗളിക്',
      mr: 'मंगळिक',
      gu: 'મંગળિક',
      bn: 'মঙ্গলিক',
      pa: 'ਮੰਗਲਿਕ',
    },
    'religion': {
      en: 'Religion',
      hi: 'धर्म',
      ta: 'மதம்',
      te: 'మతం',
      kn: 'ಧರ್ಮ',
      ml: 'മതം',
      mr: 'धर्म',
      gu: 'ધર્મ',
      bn: 'ধর্ম',
      pa: 'ਧਰਮ',
    },
    'caste': {
      en: 'Caste',
      hi: 'जाति',
      ta: 'சாதி',
      te: 'కులం',
      kn: 'ಜಾತಿ',
      ml: 'ജാതി',
      mr: 'जात',
      gu: 'જાતિ',
      bn: 'জাতি',
      pa: 'ਜਾਤ',
    },
    'motherTongue': {
      en: 'Mother Tongue',
      hi: 'मातृभाषा',
      ta: 'தாய்மொழி',
      te: 'తల్లి భాష',
      kn: 'ಮಾತೃಭಾಷೆ',
      ml: 'മാതൃഭാഷ',
      mr: 'मातृभाषा',
      gu: 'માતૃભાષા',
      bn: 'মাতৃভাষা',
      pa: 'ਮਾਂ ਬੋਲੀ',
    },
    'gothra': {
      en: 'Gothra',
      hi: 'गोत्र',
      ta: 'கோத்திரம்',
      te: 'గోత్రం',
      kn: 'ಗೋತ್ರ',
      ml: 'ഗോത്രം',
      mr: 'गोत्र',
      gu: 'ગોત્ર',
      bn: 'গোত্র',
      pa: 'ਗੋਤਰ',
    },
    'education': {
      en: 'Education',
      hi: 'शिक्षा',
      ta: 'கல்வி',
      te: 'విద్య',
      kn: 'ಶಿಕ್ಷಣ',
      ml: 'വിദ്യാഭ്യാസം',
      mr: 'शिक्षण',
      gu: 'શિક્ષણ',
      bn: 'শিক্ষা',
      pa: 'ਸਿੱਖਿਆ',
    },
    'collegeUniversity': {
      en: 'College/University',
      hi: 'कॉलेज/विश्वविद्यालय',
      ta: 'கல்லூரி/பல்கலைக்கழகம்',
      te: 'కాలేజీ/విశ్వవిద్యాలయం',
      kn: 'ಕಾಲೇಜು/ವಿಶ್ವವಿದ್ಯಾಲಯ',
      ml: 'കോളേജ്/യൂണിവേഴ്സിറ്റി',
      mr: 'कॉलेज/विश्वविद्यालय',
      gu: 'કોલેજ/યુનિવર્સિટી',
      bn: 'কলেজ/বিশ্ববিদ্যালয়',
      pa: 'ਕਾਲਜ/ਯੂਨੀਵਰਸਿਟੀ',
    },
    'occupation': {
      en: 'Occupation',
      hi: 'पेशा',
      ta: 'தொழில்',
      te: 'వృత్తి',
      kn: 'ವೃತ್ತಿ',
      ml: 'തൊഴിൽ',
      mr: 'व्यवसाय',
      gu: 'વ્યવસાય',
      bn: 'পেশা',
      pa: 'ਕਿੱਤਾ',
    },
    'annualIncome': {
      en: 'Annual Income',
      hi: 'वार्षिक आय',
      ta: 'ஆண்டு வருமானம்',
      te: 'సంవత్సర ఆదాయం',
      kn: 'ವಾರ್ಷಿಕ ಆದಾಯ',
      ml: 'വാർഷിക വരുമാനം',
      mr: 'वार्षिक उत्पन्न',
      gu: 'વાર્ષિક આવક',
      bn: 'বার্ষিক আয়',
      pa: 'ਸਾਲਾਨਾ ਆਮਦਨੀ',
    },
    'fatherOccupation': {
      en: "Father's Occupation",
      hi: 'पिता का पेशा',
      ta: 'தந்தையின் தொழில்',
      te: 'తండ్రి వృత్తి',
      kn: 'ತಂದೆಯ ವೃತ್ತಿ',
      ml: 'അച്ഛന്റെ തൊഴിൽ',
      mr: 'वडिलांचा व्यवसाय',
      gu: 'પિતાનો વ્યવસાય',
      bn: 'পিতার পেশা',
      pa: 'ਪਿਤਾ ਦਾ ਕਿੱਤਾ',
    },
    'motherOccupation': {
      en: "Mother's Occupation",
      hi: 'मां का पेशा',
      ta: 'தாயின் தொழில்',
      te: 'తల్లి వృత్తి',
      kn: 'ತಾಯಿಯ ವೃತ್ತಿ',
      ml: 'അമ്മയുടെ തൊഴിൽ',
      mr: 'आईचा व्यवसाय',
      gu: 'માતાનો વ્યવસાય',
      bn: 'মায়ের পেশা',
      pa: 'ਮਾਂ ਦਾ ਕਿੱਤਾ',
    },
    'siblings': {
      en: 'Siblings',
      hi: 'भाई-बहन',
      ta: 'சகோதரர்கள்',
      te: 'సోదరులు',
      kn: 'ಸಹೋದರರು',
      ml: 'സഹോദരങ്ങൾ',
      mr: 'भावंडे',
      gu: 'ભાઈ-બહેન',
      bn: 'ভাইবোন',
      pa: 'ਭੈਣ-ਭਰਾ',
    },
    'familyType': {
      en: 'Family Type',
      hi: 'परिवार का प्रकार',
      ta: 'குடும்ப வகை',
      te: 'కుటుంబ రకం',
      kn: 'ಕುಟುಂಬದ ಪ್ರಕಾರ',
      ml: 'കുടുംബ തരം',
      mr: 'कुटुंब प्रकार',
      gu: 'કુટુંબ પ્રકાર',
      bn: 'পরিবারের ধরন',
      pa: 'ਪਰਿਵਾਰਕ ਕਿਸਮ',
    },
    'diet': {
      en: 'Diet',
      hi: 'आहार',
      ta: 'உணவு',
      te: 'ఆహారం',
      kn: 'ಆಹಾರ',
      ml: 'ആഹാരം',
      mr: 'आहार',
      gu: 'આહાર',
      bn: 'খাদ্য',
      pa: 'ਖੁਰਾਕ',
    },
    'smoking': {
      en: 'Smoking',
      hi: 'धूम्रपान',
      ta: 'புகைப்பழக்கம்',
      te: 'ధూమపానం',
      kn: 'ಧೂಮಪಾನ',
      ml: 'പുകവലി',
      mr: 'धूम्रपान',
      gu: 'ધૂમ્રપાન',
      bn: 'ধূমপান',
      pa: 'ਸਿਗਰਟ ਪੀਣਾ',
    },
    'drinking': {
      en: 'Drinking',
      hi: 'शराब पीना',
      ta: 'குடிப்பழக்கம்',
      te: 'తాగడం',
      kn: 'ಕುಡಿಯುವುದು',
      ml: 'കുടിവെള്ളം',
      mr: 'पेय',
      gu: 'પીણું',
      bn: 'মদ্যপান',
      pa: 'ਸ਼ਰਾਬ ਪੀਣਾ',
    },
    'hobbiesInterests': {
      en: 'Hobbies & Interests',
      hi: 'शौक और रुचियां',
      ta: 'விருப்பங்கள் மற்றும் ஆர்வங்கள்',
      te: 'అభిరుచులు మరియు ఆసక్తులు',
      kn: 'ಹವ್ಯಾಸಗಳು ಮತ್ತು ಆಸಕ್ತಿಗಳು',
      ml: 'ഹോബികളും താൽപ്പര്യങ്ങളും',
      mr: 'छंद आणि आवडी',
      gu: 'શોખ અને રુચિઓ',
      bn: 'শখ ও আগ্রহ',
      pa: 'ਸ਼ੌਕ ਅਤੇ ਦਿਲਚਸਪੀਆਂ',
    },
    'city': {
      en: 'City',
      hi: 'शहर',
      ta: 'நகரம்',
      te: 'నగరం',
      kn: 'ನಗರ',
      ml: 'നഗരം',
      mr: 'शहर',
      gu: 'શહેર',
      bn: 'শহর',
      pa: 'ਸ਼ਹਿਰ',
    },
    'state': {
      en: 'State',
      hi: 'राज्य',
      ta: 'மாநிலம்',
      te: 'రాష్ట్రం',
      kn: 'ರಾಜ್ಯ',
      ml: 'സംസ്ഥാനം',
      mr: 'राज्य',
      gu: 'રાજ્ય',
      bn: 'রাজ্য',
      pa: 'ਰਾਜ',
    },
    'country': {
      en: 'Country',
      hi: 'देश',
      ta: 'நாடு',
      te: 'దేశం',
      kn: 'ದೇಶ',
      ml: 'രാജ്യം',
      mr: 'देश',
      gu: 'દેશ',
      bn: 'দেশ',
      pa: 'ਦੇਸ਼',
    },
    'citizenship': {
      en: 'Citizenship',
      hi: 'नागरिकता',
      ta: 'குடியுரிமை',
      te: 'పౌరసత్వం',
      kn: 'ನಾಗರಿಕತೆ',
      ml: 'പൗരത്വം',
      mr: 'नागरिकत्व',
      gu: 'નાગરિકતા',
      bn: 'নাগরিকত্ব',
      pa: 'ਨਾਗਰਿਕਤਾ',
    },
    'profileStats': {
      en: 'Profile Stats',
      hi: 'प्रोफ़ाइल आंकड़े',
      ta: 'சுயவிவர புள்ளிவிவரங்கள்',
      te: 'ప్రొఫైల్ గణాంకాలు',
      kn: 'ಪ್ರೊಫೈಲ್ ಅಂಕಿಅಂಶಗಳು',
      ml: 'പ്രൊഫൈൽ സ്ഥിതിവിവരക്കണക്കുകൾ',
      mr: 'प्रोफाइल आकडे',
      gu: 'પ્રોફાઇલ આંકડા',
      bn: 'প্রোফাইল পরিসংখ্যান',
      pa: 'ਪ੍ਰੋਫਾਈਲ ਅੰਕੜੇ',
    },
    'profileViews': {
      en: 'Profile Views',
      hi: 'प्रोफ़ाइल दृश्य',
      ta: 'சுயவிவர பார்வைகள்',
      te: 'ప్రొఫైల్ వీక్షణలు',
      kn: 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಣೆಗಳು',
      ml: 'പ്രൊഫൈൽ കാഴ്ചകൾ',
      mr: 'प्रोफाइल दृश्ये',
      gu: 'પ્રોફાઇલ દૃશ્યો',
      bn: 'প্রোফাইল ভিউ',
      pa: 'ਪ੍ਰੋਫਾਈਲ ਦੇਖਣ',
    },
    'completeness': {
      en: 'Completeness',
      hi: 'पूर्णता',
      ta: 'முழுமை',
      te: 'సంపూర్ణత',
      kn: 'ಸಂಪೂರ್ಣತೆ',
      ml: 'സമ്പൂർണ്ണത',
      mr: 'पूर्णता',
      gu: 'સંપૂર્ણતા',
      bn: 'সম্পূর্ণতা',
      pa: 'ਸੰਪੂਰਨਤਾ',
    },
    'trustScore': {
      en: 'Trust Score',
      hi: 'विश्वास स्कोर',
      ta: 'நம்பிக்கை மதிப்பெண்',
      te: 'విశ్వాస స్కోర్',
      kn: 'ವಿಶ್ವಾಸ ಸ್ಕೋರ್',
      ml: 'വിശ്വാസ സ്കോർ',
      mr: 'विश्वास स्कोर',
      gu: 'વિશ્વાસ સ્કોર',
      bn: 'বিশ্বাস স্কোর',
      pa: 'ਭਰੋਸਾ ਸਕੋਰ',
    },
    'photoGallery': {
      en: 'Photo Gallery',
      hi: 'फोटो गैलरी',
      ta: 'புகைப்பட கேலரி',
      te: 'ఫోటో గ్యాలరీ',
      kn: 'ಫೋಟೋ ಗ್ಯಾಲರಿ',
      ml: 'ഫോട്ടോ ഗാലറി',
      mr: 'फोटो गॅलरी',
      gu: 'ફોટો ગેલેરી',
      bn: 'ফটো গ্যালারি',
      pa: 'ਫੋਟੋ ਗੈਲਰੀ',
    },
    'notSpecified': {
      en: 'Not specified',
      hi: 'निर्दिष्ट नहीं',
      ta: 'குறிப்பிடப்படவில்லை',
      te: 'నిర్దిష్టం చేయలేదు',
      kn: 'ನಿರ್ದಿಷ್ಟಪಡಿಸಲಾಗಿಲ್ಲ',
      ml: 'നിർദ്ദേശിച്ചിട്ടില്ല',
      mr: 'निर्दिष्ट नाही',
      gu: 'નિર્દિષ્ટ નથી',
      bn: 'নির্দিষ্ট করা হয়নি',
      pa: 'ਨਿਰਧਾਰਤ ਨਹੀਂ',
    },
    'yes': {
      en: 'Yes',
      hi: 'हाँ',
      ta: 'ஆம்',
      te: 'అవును',
      kn: 'ಹೌದು',
      ml: 'അതെ',
      mr: 'होय',
      gu: 'હા',
      bn: 'হ্যাঁ',
      pa: 'ਹਾਂ',
    },
    'no': {
      en: 'No',
      hi: 'नहीं',
      ta: 'இல்லை',
      te: 'లేదు',
      kn: 'ಇಲ್ಲ',
      ml: 'ഇല്ല',
      mr: 'नाही',
      gu: 'ના',
      bn: 'না',
      pa: 'ਨਹੀਂ',
    },
    'removed': {
      en: 'removed',
      hi: 'हटा दिया गया',
      ta: 'நீக்கப்பட்டது',
      te: 'తీసివేయబడింది',
      kn: 'ತೆಗೆದುಹಾಕಲಾಗಿದೆ',
      ml: 'നീക്കംചെയ്തു',
      mr: 'काढले',
      gu: 'દૂર કર્યું',
      bn: 'সরানো হয়েছে',
      pa: 'ਹਟਾਇਆ ਗਿਆ',
    },
    'failed': {
      en: 'failed',
      hi: 'असफल',
      ta: 'தோல்வி',
      te: 'విఫలమైంది',
      kn: 'ವಿಫಲವಾಗಿದೆ',
      ml: 'പരാജയപ്പെട്ടു',
      mr: 'अयशस्वी',
      gu: 'નિષ્ફળ',
      bn: 'ব্যর্থ',
      pa: 'ਅਸਫਲ',
    },
  };

  constructor(private prisma: PrismaService) {}

  async getTranslations(language: string = 'en'): Promise<{ [key: string]: string }> {
    const result: { [key: string]: string } = {};

    Object.keys(this.translations).forEach(key => {
      result[key] = this.translations[key][language] || this.translations[key]['en'];
    });

    return result;
  }

  async translate(key: string, language: string = 'en'): Promise<string> {
    if (this.translations[key]) {
      return this.translations[key][language] || this.translations[key]['en'] || key;
    }
    return key;
  }

  async getSupportedLanguages(): Promise<Array<{ code: string; name: string; nativeName: string }>> {
    return [
      { code: 'en', name: 'English', nativeName: 'English' },
      { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
      { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
      { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
      { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
      { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
      { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
      { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
      { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
      { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
    ];
  }

  async convertCurrency(amount: number, fromCurrency: string, toCurrency: string): Promise<number> {
    // In production, use a currency conversion API (e.g., ExchangeRate-API, Fixer.io)
    // For now, return mock conversion rates

    const exchangeRates: { [key: string]: number } = {
      'USD': 1,
      'INR': 83.0,
      'EUR': 0.92,
      'GBP': 0.79,
      'AED': 3.67,
      'SAR': 3.75,
    };

    const fromRate = exchangeRates[fromCurrency.toUpperCase()] || 1;
    const toRate = exchangeRates[toCurrency.toUpperCase()] || 1;

    return (amount / fromRate) * toRate;
  }

  async getUserLanguage(userId: string): Promise<string> {
    const user = await this.prisma.user.findUnique({
      where: { id: userId },
      select: { preferredLanguage: true },
    });

    return user?.preferredLanguage || 'en';
  }

  async setUserLanguage(userId: string, language: string): Promise<void> {
    await this.prisma.user.update({
      where: { id: userId },
      data: { preferredLanguage: language },
    });
  }
}

